import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {words} from "../utils/words"
import {useState} from "react";


const randomWord = () => words[Math.floor(Math.random() * words.length)]

const Home: NextPage = () => {
	const [word, setWord] = useState("Click the button to choose a word")

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
	        {word}
        </h1>
	      <button onClick={() => {setWord(randomWord())}}>Get New Word</button>
      </main>

      <footer className={styles.footer}>
        Made by Sean, innit.
      </footer>
    </div>
  )
}

export default Home
